---
- hosts: all
  become: True

  tasks:    
    - name: Install plugin
      jenkins_plugin:
        name: "{{ item }}"
        url_username: admin
        url_password: admin
        url: http://192.168.100.100:8080
      with_items:
      - ace-editor
      - analysis-model-api
      - ant
      - antisamy-markup-formatter
      - apache-httpcomponents-client-4-api
      - bootstrap4-api
      - bouncycastle-api
      - branch-api
      - build-timeout
      - checks-api
      - cloudbees-folder
      - command-launcher
      - convert-to-pipeline
      - credentials
      - credentials-binding
      - data-tables-api
      - display-url-api
      - durable-task
      - echarts-api
      - email-ext
      - font-awesome-api
      - forensics-api
      - git
      - git-client
      - git-server
      - github
      - github-api
      - github-branch-source
      - gradle
      - greenballs
      - handlebars
      - jackson2-api
      - jaxb
      - jdk-tool
      - jjwt-api
      - jquery3-api
      - jsch
      - junit
      - ldap
      - lockable-resources
      - mailer
      - matrix-auth
      - matrix-project
      - momentjs
      - okhttp-api
      - pam-auth
      - pipeline-build-step
      - pipeline-github-lib
      - pipeline-graph-analysis
      - pipeline-input-step
      - pipeline-milestone-step
      - pipeline-model-api
      - pipeline-model-definition
      - pipeline-model-extensions
      - pipeline-rest-api
      - pipeline-stage-step
      - pipeline-stage-tags-metadata
      - pipeline-stage-view
      - plain-credentials
      - plugin-util-api
      - popper-api
      - resource-disposer
      - scm-api
      - script-security
      - snakeyaml-api
      - ssh-credentials
      - ssh-slaves
      - structs
      - timestamper
      - token-macro
      - trilead-api
      - warnings-ng
      - workflow-aggregator
      - workflow-api
      - workflow-basic-steps
      - workflow-cps
      - workflow-cps-global-lib
      - workflow-durable-task-step
      - workflow-job
      - workflow-multibranch
      - workflow-scm-step
      - workflow-step-api
      - workflow-support
      - ws-cleanup
      register: my_jenkins_plugin
    
    - name: Check if restart is required by any of the unversioned plugins
      ansible.builtin.set_fact:
        jenkins_restart_required: yes
      when: item.changed
      with_items: "{{ my_jenkins_plugin.results }}"

    - name: Restart Jenkins if required
      ansible.builtin.service:
        name: jenkins
        state: restarted
      when: jenkins_restart_required


      
  

 